print("lets learn some advance sentences in German!")
print("Here are some advance sentences and their translations:")
print("Wie geht es Ihnen? - How are you?")
print("Könnten Sie das bitte wiederholen? - Could you please repeat that?")
print("Ich habe eine Frage - I have a question")
print("Können Sie mir helfen? - Can you help me?")
print("Ich verstehe nicht - I don't understand")
print("Was empfehlen Sie? - What do you recommend?")
print("Ich bin hungrig - I am hungry")
print("Ich bin durstig - I am thirsty")
print("Können Sie das bitte langsamer sprechen? - Can you please speak more slowly?")
print("Wo ist die nächste U-Bahn-Station? - Where is the nearest subway station?")
print("Wie komme ich zum Flughafen? - How do I get to the airport?")
print("Ich hätte gern einen Tisch für zwei Personen - I would like a table for two people")
print("Könnten Sie mir die Speisekarte bringen? - Could you bring me the menu?")
print("Die Rechnung, bitte - The bill, please")