print("now let's learn some advance words in German!")
print("Here are some advance words and their translations:")
print("environment - Umwelt")
print("development - Entwicklung")
print("technology - Technologie")
print("education - Bildung")
print("government - Regierung")
print("community - Gemeinschaft")
print("opportunity - Gelegenheit")
print("responsibility - Verantwortung")
print("achievement - Leistung")
print("challenge - Herausforderung")
print("solution - Lösung")
print("innovation - Innovation")
print("sustainability - Nachhaltigkeit")