print("Now let's learn some basic words in German!")
print("Here are some common words and their translations:")
print("Hello - Hallo")
print("coffee - Kaffee")
print("water - Wasser")
print("please - bitte")
print("thank you - danke")
print("yes - ja")
print("no - nein")
print("milk - Milch")
print("bread - Brot")
print("cheese - Käse")
print("bier - beer")
print("wine - Wein")
print("juice - Saft")