print("lets learn some basic sentences in German!")
print("Here are some basic sentences and their translations:")
print("kaffee oder tee? - coffee or tea?")
print("Bier bitte - beer please")
print("wasser und brot - water and bread")
print("danke schön - thank you very much")
print("ja, ich möchte - yes, I would like")
print("nein, danke - no, thank you")
print("ich hätte gern - I would like to have")
print("milch und käse - milk and cheese")
print("ein glas wein - a glass of wine")
print("ein saft, bitte - a juice, please")
print("ich mag musik - I like music")