print("Lets learn some intermidiate words in German!")
print("Here are some intermidiate words and their translations:")
print("friend - Freund")
print("family - Familie")
print("school - Schule")
print("work - Arbeit")
print("city - Stadt")
print("country - Land")
print("car - Auto")
print("bicycle - Fahrrad")
print("book - Buch")
print("music - Musik")
print("movie - Film")
print("computer - Computer")
print("phone - Telefon")
print("table - Tisch")