print("lets learn some intermidiate sentences in German!")
print("Here are some intermidiate sentences and their translations:")
print("Wie geht's? - How are you?")
print("Ich heiße... - My name is...")
print("Ich komme aus... - I come from...")
print("Ich spreche ein bisschen Deutsch - I speak a little German")
print("Können Sie das bitte wiederholen? - Can you please repeat that?")
print("Sprechen Sie Englisch? - Do you speak English?")
print("Wo ist die Toilette? - Where is the bathroom?")
print("Wie viel kostet das? - How much does that cost?")
print("Ich hätte gern... - I would like...")
print("Können Sie mir helfen? - Can you help me?")
print("Ich verstehe nicht - I don't understand")
print("Was empfehlen Sie? - What do you recommend?")
print("Ich bin hungrig - I am hungry")
print("Ich bin durstig - I am thirsty")