print("Welcome to GermanMania")
print("This app will help you learn German in a fun and interactive way!")
print("Let's get started!")
print("what is your name?")
name = input("Enter your name: ")
print(f"Hello, {name}! Let's begin your German learning journey!")
print("In this app, you'll learn basic words, phrases, and grammar.")
print("You'll also get to practice with quizzes and interactive exercises.")
print("Are you ready to start learning German? Let's go!")